import React from 'react';
import './TokenomicsPage.css';
import NativeChart from './NativeChart';
import { nativeToken } from '../data/stocks';
import { TrendingUp } from 'lucide-react';

function TokenomicsPage() {
  return (
    <div className="tokenomics-page">
      <div className="tokenomics-hero">
        <div className="tokenomics-hero-inner">
          <h1 className="tokenomics-title">Tokenomics & Yield</h1>
          <p className="tokenomics-subtitle">
            BAWSAQ operates on a revolutionary dividend model powered by Pons.
          </p>
        </div>
      </div>

      <div className="tokenomics-section">
        <div className="section-tag">Architecture</div>
        <h2 className="section-title">The Pons Dividend Engine</h2>
        <div className="tokenomics-card">
          <div className="tokenomics-card-header">
            <h3>How It Works</h3>
          </div>
          <div className="tokenomics-card-body">
            <p>
              You launch straight from your wallet. Pons receives the creator fees generated by the platform.
            </p>
            <p>
              Instead of hoarding those fees, Pons uses them to systematically airdrop stock dividends directly to <strong>$BAWSAQ</strong> holders. You earn real value just by keeping your tokens in your wallet.
            </p>
          </div>
        </div>
      </div>

      <div className="tokenomics-section">
        <div className="section-tag">Phase 1</div>
        <h2 className="section-title">Pons Integration</h2>
        <div className="tokenomics-content-block">
          <p>
            In Phase 1, BAWSAQ partners closely with <strong>Ponsfamily.com</strong>. By launching through this ecosystem, we ensure that early holders and liquidity providers are consistently rewarded without needing to rely on complicated transfer taxes or staking lockups.
          </p>
          <p>
            As volume flows through the terminal, creator fees are captured and converted into airdropped stock dividends, creating a powerful incentive to hold and accumulate $BAWSAQ.
          </p>
        </div>
        
        <div className="chart-container">
          <div className="chart-header">
            <h3>$BAWSAQ Chart</h3>
            {nativeToken.contract ? (
              <span className="live-badge">Live</span>
            ) : (
              <span className="live-badge disabled">CA Not Live</span>
            )}
          </div>
          {nativeToken.contract ? (
            <div className="chart-iframe-wrapper">
              <NativeChart contractAddress={nativeToken.contract} />
            </div>
          ) : (
            <div className="chart-placeholder">
              <TrendingUp size={48} className="placeholder-icon" />
              <p>Chart will be available once the token is live.</p>
            </div>
          )}
        </div>
      </div>

      <div className="tokenomics-section">
        <div className="section-tag">Expansion</div>
        <h2 className="section-title">The Global Ecosystem</h2>
        <div className="tokenomics-content-block">
          <p>
            The NASDAQ runs on liquidity and listing fees; BAWSAQ runs on community dividends. To ignite the terminal's volume, our core team will deploy the first wave of 'Blue Chip' GTA stocks.
          </p>
          <p>
            But the vision extends far beyond our own deployments. Developers launching stocks on <em>any</em> platform can list on BAWSAQ. By integrating with Pons, we create a unified hub where trading volume systematically benefits the core ecosystem and its holders. Just like holding shares of a traditional stock exchange, holding <strong>$BAWSAQ</strong> means you own a piece of the house.
          </p>
        </div>
      </div>

      <div className="tokenomics-section">
        <div className="section-tag">Phase 3</div>
        <h2 className="section-title">The Vice City Expansion & RP Integration</h2>
        <div className="tokenomics-content-block">
          <p>
            The future of BAWSAQ extends directly into the streets. We are laying the groundwork for deep <strong>FiveM & GTA RP Server Integrations</strong>, allowing players to trade real crypto assets on their in-game phones and embedding the BAWSAQ economy directly into virtual worlds. Our ultimate goal is to launch an exclusive BAWSAQ-branded RP Server for our core community.
          </p>
          <p>
            As the highly anticipated launch of GTA VI approaches, we will be executing one of the largest community reward initiatives on Robinhood Chain. Top loyal shareholders will receive exclusive airdrops, insider access, and actual <strong>gifted copies of GTA VI</strong> on release day as a thank you for their unwavering support.
          </p>
        </div>
      </div>

      <div className="tokenomics-section">
        <div className="section-tag">Ecosystem</div>
        <h2 className="section-title">What is Take-Two?</h2>
        <div className="tokenomics-content-block">
          <p>
            <strong>Take-Two Interactive</strong> is the massive parent company behind Rockstar Games, the creators of the Grand Theft Auto series. In the context of the BAWSAQ ecosystem, tracking the Take-Two (TTWO) tokenized stock serves as a major bellwether for the health and hype of the GTA economy on-chain.
          </p>
          <p>
            By integrating Take-Two's price action into our terminal, users can trade and hedge against the macro performance of the very studio that built the HD universe.
          </p>
          <p>
            <strong>Where to trade TTWO:</strong> You can find and trade the TTWO tokenized stock directly on Backpack Exchange, via decentralized exchanges like Raydium, or by searching the contract address on DexScreener.
          </p>
        </div>

        <div className="chart-container">
          <div className="chart-header">
            <h3>Take-Two (Tokenized Stock on Robinhood Chain)</h3>
            <span className="live-badge">Live</span>
          </div>
          <div className="chart-iframe-wrapper">
            <NativeChart contractAddress="TTWofwAge91oFhZs7kpQdyrVRkmevgM88xijGvQFbKo" />
          </div>
        </div>
      </div>
    </div>
  );
}

export default TokenomicsPage;
